name: M3U Playlist Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Her Pazartesi 00:00'da

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Create last_episode file if not exists
      run: |
        if [ ! -f "last_episode.txt" ]; then
          echo "194" > last_episode.txt
        fi
    
    - name: Generate M3U
      run: python generate_m3u.py
    
    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git diff --quiet && git diff --cached --quiet || git commit -m "Otomatik g√ºncelleme: $(date +'%d.%m.%Y %H:%M')"
        git push
